name: qcportal
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - msgpack-python>=0.6.1
  - numpy
  - pandas
  - requests
  - pydantic >=1.0
  - pyyaml >=5.1
  - plotly
  - nglview
  - h5py
  - tqdm
  - pyarrow>=0.13.0
  - double-conversion>=3.0.0

# Test depends
  - pytest
  - pytest-cov
  - codecov

# QCArchive includes
  - qcelemental>=0.9
