name: qcportal
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - msgpack-python>=0.6.1
  - numpy
  - pandas
  - requests
  - pydantic >=0.32
  - pyyaml >=5.1
  - plotly
  - py3dmol
  - h5py

# Test depends
  - pytest
  - pytest-cov
  - codecov

# QCArchive includes
  - qcelemental>=0.6
