language: python

# Run jobs on container-based infrastructure, can be overridden per job
dist: trusty

matrix:
  include:
    # Extra includes for OSX since python language is not available by default on OSX
    - os: osx
      language: generic
      env: PYTHON_VER=3.5
    - os: osx
      language: generic
      env: PYTHON_VER=3.6
    - os: osx
      language: generic
      env: PYTHON_VER=3.7

    - os: linux
      python: 3.5
      env: PYTHON_VER=3.5
    - os: linux
      python: 3.6
      env: PYTHON_VER=3.6
    - os: linux
      python: 3.7
      env: PYTHON_VER=3.7


before_install:
    # Additional info about the build
  - uname -a
  - df -h
  - ulimit -a

    # Install the Python environment
  - source devtools/travis-ci/before_install.sh
  - python -V

install:

    # Create test environment for package
  - conda create -n test python=$PYTHON_VER pip pytest pytest-cov
  - conda activate test

    # Install pip only modules
  - pip install codecov

    # Build and install package
  - conda build --python=$PYTHON_VER devtools/conda-recipe
  - conda install --use-local qcportal


script:
  - pytest -v --cov=qcportal qcportal/tests/

notifications:
    email: false

after_success:
  - codecov
