name: Build and Deploy Docs

on:
  push:
    branches:
      - test_docs
  pull_request:
    branches:
      - test_docs

jobs:
  deploy_docs:
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # needed for tag/version

      - name: Install pandoc
        run: sudo apt install -y pandoc

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install package
        shell: bash -l {0}
        run: |
          python -m pip install .[docs]

      - name: Build Documentation
        run: |
          cd docs
          make html

      - name: Deploy Documentation
        uses: JamesIves/github-pages-deploy-action@4.1.1
        if: github.event_name == 'push'
        with:
          token: ${{ secrets.QCABOT_PAT }}
          repository-name: MolSSI/QCArchiveWebsite
          branch: gh-pages
          target-folder: docs/qcportal
          folder: docs/build/html
